### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by betchasketch** [martinux/proton_pack_arduino#2]
I know this is an older thread but do you happen to have photos or a finished diagram with the soundboard and cyclotron lights attached to the arduino?

**Comment by martinux** [comment]
Hi there, sorry for the delay in responding.

Unfortunately I do not. Most of the circuitry is built on strip-board so it's probably not what you'd want to build if you were after reliability. The sound board is from Adafruit: (https://www.adafruit.com/product/94), it has been very easy to use though there may be something more capable available since I built the proton pack.

The Cyclotron lights run off a 555 timer and a 4017 decade counter. I could have used a pin on the arduino to change the cyclotron light speed but I already had the circuit built (again on stripboard).

Best of luck with your build.
